apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: torrentbox
  labels:
    app: sonarr
spec:
  replicas: 1
  # Revert to default RollingUpdate strategy
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        # Remove gluetun config volume
        # - name: gluetun-config-hostpath
        #   hostPath:
        #     path: /Users/haashimalvi/git_repo/torrentBox-kubernetes/config/gluetun
        #     type: DirectoryOrCreate
        - name: sonarr-config-hostpath
          hostPath:
            path: /Users/haashimalvi/git_repo/torrentBox-kubernetes/config/sonarr
            type: DirectoryOrCreate
        - name: main-data # Mount the consolidated data volume
          persistentVolumeClaim:
            claimName: main-data-pvc
        # Remove /dev/net/tun volume
        # - name: dev-net-tun
        #   hostPath:
        #     path: /dev/net/tun
        #     type: CharDevice
      containers:
        # Remove gluetun container
        # - name: gluetun
        #   ... (removed) ...

        - name: sonarr # Now the only container
          # Using linux/arm64 explicitly as specified in compose
          image: lscr.io/linuxserver/sonarr:latest # platform handled by k8s node selector or runtime class if needed
          imagePullPolicy: IfNotPresent
          ports: # Expose ports directly on this container
            - name: sonarr-webui # Use the same name as the service targetPort will use
              containerPort: 8989 # Port from compose file
              protocol: TCP
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: TZ
            - name: UMASK # Added UMASK from compose example (implicitly 022 if not set, but good to be explicit)
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: UMASK # Corrected this from TZ
          volumeMounts:
            - name: sonarr-config-hostpath # Use hostPath volume
              mountPath: /config
            - name: main-data # Mount the consolidated volume
              mountPath: /data # Sonarr expects media/downloads here for hardlinks
          readinessProbe:
            httpGet:
              path: /ping # Sonarr's ping endpoint
              port: 8989 # Internal port Sonarr listens on
            initialDelaySeconds: 20 # Give time for Sonarr to start
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
