apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: torrentbox
  labels:
    app: bazarr
spec:
  replicas: 1
  # Revert to default RollingUpdate strategy
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        # Remove gluetun config volume
        # - name: gluetun-config-hostpath
        #   hostPath:
        #     path: /Users/haashimalvi/git_repo/torrentBox-kubernetes/config/gluetun
        #     type: DirectoryOrCreate
        - name: bazarr-config-hostpath
          hostPath:
            path: /Users/haashimalvi/git_repo/torrentBox-kubernetes/config/bazarr/config
            type: DirectoryOrCreate
        - name: main-data # Mount the consolidated data volume
          persistentVolumeClaim:
            claimName: main-data-pvc
        # Remove /dev/net/tun volume
        # - name: dev-net-tun
        #   hostPath:
        #     path: /dev/net/tun
        #     type: CharDevice
      containers:
        # Remove gluetun container
        # - name: gluetun
        #   ... (removed) ...

        - name: bazarr # Now the only container
          # Using linux/arm64 explicitly as specified in compose
          image: lscr.io/linuxserver/bazarr:latest # platform handled by k8s node selector or runtime class if needed
          imagePullPolicy: IfNotPresent
          ports: # Expose ports directly on this container
            - name: bazarr-webui # Use the same name as the service targetPort will use
              containerPort: 6767 # Port from compose file
              protocol: TCP
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: TZ
            - name: UMASK # Added UMASK from compose example
              valueFrom:
                configMapKeyRef:
                  name: torrentbox-config
                  key: UMASK
          volumeMounts:
            - name: bazarr-config-hostpath # Use hostPath volume
              mountPath: /config
            - name: main-data # Mount the consolidated volume
              mountPath: /data # Bazarr needs access to media folder specified in compose (/data/media)
              # Note: The original compose mounted /data/media, here we mount /data
              # and expect Bazarr to be configured internally to look within /data/media
          readinessProbe:
            tcpSocket:
              port: 6767 # Check if the process is listening internally
            initialDelaySeconds: 20 # Give time for Bazarr to start
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
