apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Gluetun
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for qBittorrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitrr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for qbitrr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Lidarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Radarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Bazarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Jellyseer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Sabnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Config for Prowlarr
---
# Consolidated Data Volume for Hardlinks/Atomic Moves
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-data-pvc
  namespace: torrentbox
spec:
  accessModes:
    - ReadWriteOnce # Assumes Pods needing this run on the same node or use shared storage if scaled
  resources:
    requests:
      storage: 2Ti # Combined storage for torrents, usenet, media - adjust size as needed
